USE [master]
GO
/****** Object:  Database [QlSieuThi]    Script Date: 11/22/2022 6:46:57 PM ******/
CREATE DATABASE [QlSieuThi]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QlSieuThi', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\QlSieuThi.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QlSieuThi_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\QlSieuThi_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [QlSieuThi] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QlSieuThi].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [QlSieuThi] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [QlSieuThi] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [QlSieuThi] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [QlSieuThi] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [QlSieuThi] SET ARITHABORT OFF 
GO
ALTER DATABASE [QlSieuThi] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [QlSieuThi] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [QlSieuThi] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [QlSieuThi] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [QlSieuThi] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [QlSieuThi] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [QlSieuThi] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [QlSieuThi] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [QlSieuThi] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [QlSieuThi] SET  DISABLE_BROKER 
GO
ALTER DATABASE [QlSieuThi] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [QlSieuThi] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [QlSieuThi] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [QlSieuThi] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [QlSieuThi] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [QlSieuThi] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [QlSieuThi] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [QlSieuThi] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [QlSieuThi] SET  MULTI_USER 
GO
ALTER DATABASE [QlSieuThi] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [QlSieuThi] SET DB_CHAINING OFF 
GO
ALTER DATABASE [QlSieuThi] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [QlSieuThi] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [QlSieuThi] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [QlSieuThi] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [QlSieuThi] SET QUERY_STORE = OFF
GO
USE [QlSieuThi]
GO
/****** Object:  Table [dbo].[ChiTietHoaDon]    Script Date: 11/22/2022 6:46:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ChiTietHoaDon](
	[maHD] [nchar](20) NOT NULL,
	[maSP] [nchar](20) NOT NULL,
	[giaTien] [float] NOT NULL,
	[soLuong] [int] NOT NULL,
	[thanhTien] [money] NULL,
PRIMARY KEY CLUSTERED 
(
	[maHD] ASC,
	[maSP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HoaDon]    Script Date: 11/22/2022 6:46:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HoaDon](
	[maHD] [nchar](20) NOT NULL,
	[ngayLapHoaDon] [datetime2](6) NULL,
	[tongTienThanhToan] [money] NULL,
	[maKH] [nchar](30) NULL,
	[maNV] [nchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[maHD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KhachHang]    Script Date: 11/22/2022 6:46:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KhachHang](
	[maKH] [nchar](30) NOT NULL,
	[CMND] [nchar](50) NULL,
	[SDT] [nchar](10) NULL,
	[diaChi] [nchar](100) NULL,
	[email] [nchar](100) NULL,
	[gioHang] [bit] NOT NULL,
	[gioiTinh] [bit] NOT NULL,
	[ngaySinh] [date] NULL,
	[tenKH] [nchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[maKH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NhanVien]    Script Date: 11/22/2022 6:46:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NhanVien](
	[maNV] [nchar](20) NOT NULL,
	[CMND] [nchar](50) NULL,
	[SDT] [nchar](10) NULL,
	[chucVu] [nchar](30) NULL,
	[diaChi] [nchar](50) NULL,
	[email] [nchar](50) NULL,
	[gioiTinh] [bit] NULL,
	[luong] [float] NOT NULL,
	[ngaySinh] [date] NULL,
	[tenNV] [nchar](50) NULL,
	[trangThai] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[maNV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SanPham]    Script Date: 11/22/2022 6:46:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SanPham](
	[maSP] [nchar](20) NOT NULL,
	[donGia] [money] NULL,
	[loaiHang] [nchar](100) NULL,
	[nhaCungCap] [nchar](100) NULL,
	[soLuong] [int] NOT NULL,
	[tenSP] [nchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[maSP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TaiKhoan]    Script Date: 11/22/2022 6:46:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TaiKhoan](
	[tenDN] [nchar](20) NOT NULL,
	[matKhau] [nchar](30) NULL,
PRIMARY KEY CLUSTERED 
(
	[tenDN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ChiTietHoaDon]  WITH CHECK ADD  CONSTRAINT [FK2kbafpq23m2cuqm32ifoiwi9d] FOREIGN KEY([maHD])
REFERENCES [dbo].[HoaDon] ([maHD])
GO
ALTER TABLE [dbo].[ChiTietHoaDon] CHECK CONSTRAINT [FK2kbafpq23m2cuqm32ifoiwi9d]
GO
ALTER TABLE [dbo].[ChiTietHoaDon]  WITH CHECK ADD  CONSTRAINT [FK6e48ooakrayatm2uq598i9a4x] FOREIGN KEY([maSP])
REFERENCES [dbo].[SanPham] ([maSP])
GO
ALTER TABLE [dbo].[ChiTietHoaDon] CHECK CONSTRAINT [FK6e48ooakrayatm2uq598i9a4x]
GO
ALTER TABLE [dbo].[HoaDon]  WITH CHECK ADD  CONSTRAINT [FKg1ebuq3tydt58wb4gutehmh9w] FOREIGN KEY([maKH])
REFERENCES [dbo].[KhachHang] ([maKH])
GO
ALTER TABLE [dbo].[HoaDon] CHECK CONSTRAINT [FKg1ebuq3tydt58wb4gutehmh9w]
GO
ALTER TABLE [dbo].[HoaDon]  WITH CHECK ADD  CONSTRAINT [FKoyaa1162ps1nyifmfv2pv2qr] FOREIGN KEY([maNV])
REFERENCES [dbo].[NhanVien] ([maNV])
GO
ALTER TABLE [dbo].[HoaDon] CHECK CONSTRAINT [FKoyaa1162ps1nyifmfv2pv2qr]
GO
ALTER TABLE [dbo].[TaiKhoan]  WITH CHECK ADD  CONSTRAINT [FKqj85tyxxhk1k6y1b4w3jehe1k] FOREIGN KEY([tenDN])
REFERENCES [dbo].[NhanVien] ([maNV])
GO
ALTER TABLE [dbo].[TaiKhoan] CHECK CONSTRAINT [FKqj85tyxxhk1k6y1b4w3jehe1k]
GO
USE [master]
GO
ALTER DATABASE [QlSieuThi] SET  READ_WRITE 
GO
